### ISSUE TITLE
IServerUrls-related issue after IdentityServer4 -> Duende IdentityServer v6, v7 migration

### ISSUE THREAD

**Issue by promim** [DuendeSoftware/Support#1265]
**Which version of Duende IdentityServer are you using?**
7.0.4

**Which version of .NET are you using?**
8.0.3

**Describe the bug**
We've just migrated our IdentityServer4 implementation to Duende IdentityServer v6 and v7 subsequently. We have had a development setup, where we run the IdentityServer implementation in a Docker container and an MVC client application (with configured OIDC) in another Docker container. It appears that after the required IServerUrls change in one of the Duende IdentityServer v6 subversions, this setup no longer works as before. 

**To Reproduce**

Steps to reproduce the behavior.

The IdentityServer implementation (referred to as `oauth`) is available at https://localhost:6501 (which is also the IServerUrls.Origin implementation)
The MVC client application (referred to as `devframe`) is available at https://localhost:31111

docker-compose looks like this

```
devframe:
  container_name: xx-oauth.devframe
  hostname: devframe
  image: temp.devframe
  build: .
  pull_policy: always
  restart: unless-stopped
  environment:
    - TZ="Europe/Copenhagen"
    - ASPNETCORE_ENVIRONMENT="Development"
    - ASPNETCORE_Kestrel__Certificates__Default__Password="password"
    - ASPNETCORE_Kestrel__Certificates__Default__Path="/https/cert-aspnetcore.pfx"
    - ASPNETCORE_URLS="https://+;http://+"
  ports:
    - "31111:443"
    - "31110:80"
  volumes:
    - "c:/local-cert:/https"

oauth:
  container_name: xx-oauth.oauth
  hostname: oauth
  build: .
  image: temp.oauth
  pull_policy: always
  restart: unless-stopped
  environment:
    - TZ="Europe/Copenhagen"
    - ASPNETCORE_ENVIRONMENT="Development"
    - ASPNETCORE_Kestrel__Certificates__Default__Password="password"
    - ASPNETCORE_Kestrel__Certificates__Default__Path="/https/cert-aspnetcore.pfx"
    - ASPNETCORE_URLS="https://+;http://+"
    - OAUTH_AUTHORITY="https://oauth"
  ports:
    - "6500:80"
    - "6501:443"
  volumes:
    - C:\local-cert:/https
```
After accessing `devframe` at https://localhost:31111 in the browser, we trigger an action that challenges the OIDC authentication scheme. Since the authority in the OIDC configuration is set to OAUTH_AUTHORITY (https://oauth), we are able to hit the discovery document endpoint, but since the JWKS URI is set to localhost:6501, `devframe` from within its container is not able to access it. 

Something around the time when the IServerUrls change was introduced seems to have caused this problem. 

**Log output/exception with stacktrace**

```
SocketException: Connection refused
System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

HttpRequestException: Connection refused (localhost:6501)
System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(string host, int port, HttpRequestMessage initialRequest, bool async, CancellationToken cancellationToken)

IOException: IDX20804: Unable to retrieve document from: 'https://localhost:6501/.well-known/openid-configuration/jwks'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)

InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://oauth/.well-known/openid-configuration'. Will retry at '23/05/2024 12:40:58 +00:00'. Exception: 'System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://localhost:6501/.well-known/openid-configuration/jwks'.
---> System.Net.Http.HttpRequestException: Connection refused (localhost:6501)
---> System.Net.Sockets.SocketException (111): Connection refused
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
```

**Additional context**

![image](https://github.com/DuendeSoftware/Support/assets/167987607/6ab1f059-326a-4287-baee-b5538483d06c)

Notice that the communication between the containers seems fine, I can ping any endpoint on `oauth` from within the `devframe` container terminal:

![image](https://github.com/DuendeSoftware/Support/assets/167987607/6318c621-8f0e-4414-af0a-a505df547bae)

Not sure if relevant, but when running the server and the client, I do get the following logs on both `devframe` and `oauth`:

```
Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'https://+;http://+'.
Overriding address(es) 'https://+, http://+'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
Now listening on: http://0.0.0.0:80
Now listening on: https://0.0.0.0:443
```

Both `devframe` and `oauth` are configured to start up with the following setup:

```
public static void Main(string[] args) => CreateWebHostBuilder(args).Build().Run();

public static IHostBuilder CreateWebHostBuilder(string[] args)
    => Host
        .CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(builder =>
        {
            builder
                .ConfigureAppConfiguration((context, config) =>
                {
                    config
                        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                        .AddEnvironmentVariables();

                    if (args is not null)
                    {
                        config.AddCommandLine(args);
                    }
                })
                .ConfigureWebHostDefaults()
                .UseStartup<Startup>();
        });

public static IWebHostBuilder ConfigureWebHostDefaults(this IWebHostBuilder builder)
    => builder
        .ConfigureKestrel((context, options) => options.AddServerHeader = false)
        .UseKestrel((context, options) =>
        {
            // retrieve certificate from specified path
            var certificate = CertificateHelper.GetX509CertificateFromDefaultConfiguration(context.Configuration);

            if (certificate is not null)
            {
                options.Listen(
                    IPAddress.Any,
                    80,
                    c =>
                    {
                        c.Protocols = HttpProtocols.Http1;
                    });

                options.Listen(
                    IPAddress.Any,
                    443,
                    c =>
                    {
                        c.UseHttps(certificate);
                        c.Protocols = HttpProtocols.Http1AndHttp2;
                    });
            }
            else
            {
                Console.WriteLine("Cannot fetch certificate from keyvault. Kestrel will default to default certificate.");
            }
        });
```
